# Generated by Django 6.0 on 2025-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
