# Generated by Django 6.0 on 2025-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_COLLECTOR_CONFIRMATION', 'Pending Collector Confirmation'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On The Way'), ('PICKED_UP', 'Picked Up'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30),
        ),
    ]
